theme = "kanagawa"

[editor]
idle-timeout = 50
completion-timeout = 5
cursorline = false
cursorcolumn = false
true-color = true
line-number = "relative"
mouse = false
auto-pairs = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"
rulers = []

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["workspace-diagnostics", "selections"]
right = ["diagnostics", "position"]

[editor.lsp]
display-messages = false
display-inlay-hints = false
auto-signature-help = false

[editor.indent-guides]
render = true
character = "⸽"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
ignore = true
git-global = false

[editor.soft-wrap]
enable = false

[editor.gutters]
layout = ["diagnostics", "line-numbers"]

[editor.search]
smart-case = true

[keys.normal.C-y]
y = ":sh zellij run -f -x 10%% -y 10%% --width 80%% --height 80%% -- fish ~/.config/helix/yazi-picker.fish $ZELLIJ_PANE_ID"
