theme = "kanagawa"

[editor]
true-color = true
line-number = "relative"
mouse = false
auto-pairs = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["workspace-diagnostics", "selections"]
right = ["diagnostics", "position", "file-encoding"]

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.indent-guides]
render = true
character = "⸽"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
ignore = true
git-global = false

[editor.soft-wrap]
enable = true

[editor.search]
smart-case = true

[keys.normal.C-y]
y = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- fish ~/.config/helix/yazi-picker.fish $ZELLIJ_PANE_ID"
