theme = "kanagawa"

[editor]
idle-timeout = 50
completion-timeout = 5
cursorline = true
cursorcolumn = false
true-color = true
color-modes = true
line-number = "relative"
mouse = true
auto-pairs = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"
rulers = []

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["workspace-diagnostics", "selections"]
right = ["diagnostics", "position"]

[editor.lsp]
display-messages = true
display-inlay-hints = false
auto-signature-help = false

[editor.indent-guides]
render = true
character = "⸽"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
ignore = true
git-global = false

[editor.soft-wrap]
enable = false

[editor.gutters]
layout = ["diagnostics", "line-numbers"]

[editor.search]
smart-case = true

[keys.normal]
C-y = [
  ":sh rm -f /tmp/yazi-chooser",
  ":insert-output yazi %{buffer_name} --chooser-file=/tmp/yazi-chooser",
  ":sh printf '\\x1b[?1049h\\x1b[?2004h' > /dev/tty",
  ":open %sh{cat /tmp/yazi-chooser 2>/dev/null}",
  ":redraw",
]