env:
  TERM: screen-256color

window:
  position:
    x: 0
    y: 0
  padding:
    x: 0
    y: 0
  dynamic_padding: false
  opacity: 1.0
  startup_mode: Windowed
  dynamic_title: true

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: VictorMono NF
    style: Regular
  bold:
    family: VictorMono NF
    style: Bold
  italic:
    family: VictorMono NF
    style: Italic
  bold_italic:
    family: VictorMono NF
  size: 16.0
  offset:
    x: 0
    y: 0

# Colors (Gruvbox)
colors:
  primary:
    background: "0x282828"
    foreground: "0xebdbb2"
  normal:
    black: "0x282828"
    red: "0xcc241d"
    green: "0x98971a"
    yellow: "0xd79921"
    blue: "0x458588"
    magenta: "0xb16286"
    cyan: "0x689d6a"
    white: "0xa89984"
  bright:
    black: "0x928374"
    red: "0xfb4934"
    green: "0xb8bb26"
    yellow: "0xfabd2f"
    blue: "0x83a598"
    magenta: "0xd3869b"
    cyan: "0x8ec07c"
    white: "0xebdbb2"

bell:
  animation: EaseOutExpo
  duration: 5
  color: "#ffffff"

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

shell:
  program: /opt/homebrew/bin//fish
