brew cask install blender
brew cask install flux
brew cask install xquartz
brew cask install inkscape
brew cask install teamviewer
brew cask install dropbox
brew cask install google-chrome
brew cask install skype
brew cask install visual-studio-code
brew cask install firefox
brew cask install hyper
brew cask install spectacle
brew cask install keycastr
