# Espanso Trigger

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # Nail Pro
  - trigger: ":nail-1"
    replace: "Thank you for your wonderful feedback! We're thrilled to be your top choice in Silverdale. It's great to hear you loved your pedicure and acrylic fill. We look forward to seeing you again soon at Nail Pro!"

  - trigger: ":nail-2"
    replace: "Thank you for your wonderful feedback! We are truly honored to offer exceptional service at Nail Pro."