# Espanso Configuration

# --- Toggle key
toggle_key: OFF
search_shortcut: OFF

# --- Injection Backend
# backend: Clipboard

# --- Auto-restart
# auto_restart: false

# --- Clipboard threshold
# clipboard_threshold: 100