matches:
  # Me
  - trigger: ";me.email"
    replace: "chieuhue@gmail.com"

  - trigger: ";me.site"
    replace: "https://dangthanh.org"

  - trigger: ";me.twitter"
    replace: "https://twitter.com/dangvanthanh"

  - trigger: ";me.github"
    replace: "https://github.com/dangvanthanh"

  - trigger: ";me.facebook"
    replace: "https://www.facebook.com/dangvanthanh"

  - trigger: ";me.linkedin"
    replace: "https://www.linkedin.com/in/dangthanh/"
