matches:
  # Thanks
  - trigger: ";ty.wonder"
    replace: "Thank you for your wonderful feedback!"

  - trigger: ";ty.feed"
    replace: "Thank you for your feedback!"

  - trigger: ";ty.generous"
    replace: "Thank you for your generous words!"

  - trigger: ";ty.kind"
    replace: "Thank you for your kind words!"

  - trigger: ";ty.sy"
    replace: "We look forward to seeing you again soon at Nail Pro!"

  - trigger: ";ty.apologize"
    replace: "We sincerely apologize for your experience. We'll ensure better service next time!"

  - trigger: ";ty.glad"
    replace: "We're glad that your time at Nail Pro was great, and we hope to see you soon!"

  - trigger: ";ty.share"
    replace: "Could you please share how we can improve?"

  - trigger: ";ty.support"
    replace: "Your support is greatly appreciated."

  - trigger: ";np.nails"
    replace: |
      Nails:

      Treat yourself to the ultimate nail experience - your dream nails are just a phone call away!
      📞 (360) 698-5063
      📍 3299 NW Randall Way #103, Silverdale, WA 98383

      #nailpro #nailprosilverdale #festivestyle

  - trigger: ";np.image"
    replace: "Provide a description of these nails in 40-60 characters."

  - trigger: ";np.reply"
    replace: "Compose a thank you reply to feedback for my salon, Nail Pro, between 100-140 characters:"