import type { ProviderModelConfig } from "@earendil-works/pi-coding-agent";

// Snapshot: 2026-09-21. https://commandcode.ai/models and linked model pages.
// Prices are USD per million tokens, after deals; DeepSeek uses off-peak rates.
// The public /v1/models endpoint does not publish this metadata.
export type ModelMetadata = {
	reasoning: boolean;
	vision: boolean;
	efforts: string[];
	cost: ProviderModelConfig["cost"];
};

export const metadata: Record<string, ModelMetadata> = {
	"poolside/laguna-s-2.1-free": {
		reasoning: true,
		vision: false,
		efforts: [],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
	},
	"meituan/LongCat-2.0": {
		reasoning: true,
		vision: false,
		efforts: [],
		cost: { input: 0.3, output: 1.2, cacheRead: 0.006, cacheWrite: 0 },
	},
	"inclusionai/ling-3.0-flash-sante:free": {
		reasoning: true,
		vision: false,
		efforts: [],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
	},
	"tencent/hy4-preview": {
		reasoning: true,
		vision: false,
		efforts: ["low", "medium", "high"],
		cost: { input: 0.834, output: 2.501, cacheRead: 0.042, cacheWrite: 0 },
	},
	"tencent/hy3-paid": {
		reasoning: true,
		vision: false,
		efforts: [],
		cost: { input: 0.14, output: 0.58, cacheRead: 0.035, cacheWrite: 0 },
	},
	"moonshotai/Kimi-K3": {
		reasoning: true,
		vision: true,
		efforts: ["low", "high", "max"],
		cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 0 },
	},
	"moonshotai/Kimi-K2.7-Code": {
		reasoning: true,
		vision: true,
		efforts: [],
		cost: { input: 0.95, output: 4, cacheRead: 0.19, cacheWrite: 0 },
	},
	"moonshotai/Kimi-K2.7-Code-Highspeed": {
		reasoning: true,
		vision: true,
		efforts: [],
		cost: { input: 1.9, output: 8, cacheRead: 0.38, cacheWrite: 0 },
	},
	"moonshotai/Kimi-K2.6": {
		reasoning: false,
		vision: true,
		efforts: [],
		cost: { input: 0.95, output: 4, cacheRead: 0.16, cacheWrite: 0 },
	},
	"moonshotai/Kimi-K2.5": {
		reasoning: false,
		vision: true,
		efforts: [],
		cost: { input: 0.6, output: 3, cacheRead: 0.1, cacheWrite: 0 },
	},
	"z-ai/glm-5.3-flash": {
		reasoning: true,
		vision: true,
		efforts: ["low", "high", "max"],
		cost: { input: 0.15, output: 0.5, cacheRead: 0.03, cacheWrite: 0 },
	},
	"z-ai/glm-5.3-flashx": {
		reasoning: true,
		vision: true,
		efforts: [],
		cost: { input: 0.37, output: 1.25, cacheRead: 0.07, cacheWrite: 0 },
	},
	"zai-org/GLM-5.3": {
		reasoning: true,
		vision: false,
		efforts: ["low", "high", "max"],
		cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
	},
	"zai-org/GLM-5.2": {
		reasoning: true,
		vision: false,
		efforts: ["high", "max"],
		cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
	},
	"zai-org/GLM-5.2-Fast": {
		reasoning: false,
		vision: false,
		efforts: [],
		cost: { input: 3, output: 10.25, cacheRead: 0.5, cacheWrite: 0 },
	},
	"zai-org/GLM-5.1": {
		reasoning: false,
		vision: false,
		efforts: [],
		cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
	},
	"zai-org/GLM-5": {
		reasoning: false,
		vision: false,
		efforts: [],
		cost: { input: 1, output: 3.2, cacheRead: 0.2, cacheWrite: 0 },
	},
	"MiniMaxAI/MiniMax-M3": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high"],
		cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0 },
	},
	"MiniMaxAI/MiniMax-M2.7": {
		reasoning: false,
		vision: false,
		efforts: [],
		cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0 },
	},
	"MiniMaxAI/MiniMax-M2.5": {
		reasoning: false,
		vision: false,
		efforts: [],
		cost: { input: 0.3, output: 1.2, cacheRead: 0.03, cacheWrite: 0 },
	},
	"deepseek/deepseek-v4.1-flash": {
		reasoning: true,
		vision: true,
		efforts: ["low", "high", "max"],
		cost: { input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: 0 },
	},
	"deepseek/deepseek-v4-pro": {
		reasoning: true,
		vision: false,
		efforts: ["high", "max"],
		cost: { input: 0.66, output: 1.98, cacheRead: 0.022, cacheWrite: 0 },
	},
	"deepseek/deepseek-v4-flash": {
		reasoning: true,
		vision: false,
		efforts: ["high", "max"],
		cost: { input: 0.22, output: 0.66, cacheRead: 0.007, cacheWrite: 0 },
	},
	"deepseek/deepseek-v4-flash-vision-exp": {
		reasoning: true,
		vision: true,
		efforts: ["high", "max"],
		cost: { input: 0.22, output: 0.66, cacheRead: 0.007, cacheWrite: 0 },
	},
	"deepseek/deepseek-v4-flash-fast": {
		reasoning: true,
		vision: false,
		efforts: ["low", "high", "max"],
		cost: { input: 0.28, output: 0.56, cacheRead: 0.07, cacheWrite: 0 },
	},
	"Qwen/Qwen3.8-Omni-Flash": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "xhigh"],
		cost: { input: 0.15, output: 0.47, cacheRead: 0.02, cacheWrite: 0 },
	},
	"Qwen/Qwen3.8-Max-0902": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "xhigh"],
		cost: { input: 2, output: 6, cacheRead: 0.25, cacheWrite: 0 },
	},
	"Qwen/Qwen3.8-Max": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "xhigh"],
		cost: { input: 2, output: 6, cacheRead: 0.25, cacheWrite: 2.5 },
	},
	"Qwen/Qwen3.8-27B": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "xhigh"],
		cost: { input: 0.4, output: 3, cacheRead: 0.04, cacheWrite: 0 },
	},
	"Qwen/Qwen3.6-Max-Preview": {
		reasoning: true,
		vision: false,
		efforts: [],
		cost: { input: 1.3, output: 7.8, cacheRead: 0.26, cacheWrite: 1.63 },
	},
	"Qwen/Qwen3.6-Plus": {
		reasoning: true,
		vision: true,
		efforts: [],
		cost: {
			input: 0.5,
			output: 3,
			cacheRead: 0.1,
			cacheWrite: 0,
			tiers: [{ inputTokensAbove: 256000, input: 2, output: 6, cacheRead: 0.2, cacheWrite: 0 }],
		},
	},
	"Qwen/Qwen3.7-Max": {
		reasoning: true,
		vision: false,
		efforts: [],
		cost: { input: 2.5, output: 7.5, cacheRead: 0.5, cacheWrite: 3.13 },
	},
	"Qwen/Qwen3.7-Plus": {
		reasoning: true,
		vision: true,
		efforts: [],
		cost: {
			input: 0.4,
			output: 1.6,
			cacheRead: 0.08,
			cacheWrite: 0.5,
			tiers: [
				{ inputTokensAbove: 256000, input: 1.2, output: 4.8, cacheRead: 0.24, cacheWrite: 1.5 },
			],
		},
	},
	"Qwen/Qwen3.8-Flash": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "xhigh"],
		cost: { input: 0.16, output: 0.47, cacheRead: 0.016, cacheWrite: 0 },
	},
	"Qwen/Qwen3.7-Flash": {
		reasoning: true,
		vision: true,
		efforts: [],
		cost: {
			input: 0.03,
			output: 0.13,
			cacheRead: 0.006,
			cacheWrite: 0.038,
			tiers: [
				{ inputTokensAbove: 32000, input: 0.1, output: 0.4, cacheRead: 0.02, cacheWrite: 0.125 },
				{ inputTokensAbove: 256000, input: 0.2, output: 0.8, cacheRead: 0.04, cacheWrite: 0.25 },
			],
		},
	},
	"stepfun/step-5-preview": {
		reasoning: true,
		vision: true,
		efforts: [],
		cost: { input: 1, output: 2.7, cacheRead: 0.05, cacheWrite: 0 },
	},
	"stepfun/Step-3.7-Flash": {
		reasoning: true,
		vision: true,
		efforts: [],
		cost: { input: 0.2, output: 1.15, cacheRead: 0.04, cacheWrite: 0 },
	},
	"stepfun/Step-3.5-Flash": {
		reasoning: true,
		vision: false,
		efforts: [],
		cost: { input: 0.1, output: 0.3, cacheRead: 0.02, cacheWrite: 0 },
	},
	"xiaomi/mimo-v2.6-pro": {
		reasoning: false,
		vision: true,
		efforts: [],
		cost: { input: 0.435, output: 0.87, cacheRead: 0.0036, cacheWrite: 0 },
	},
	"xiaomi/mimo-v2.6-pro-ultraspeed": {
		reasoning: false,
		vision: true,
		efforts: [],
		cost: { input: 4.35, output: 8.7, cacheRead: 0.036, cacheWrite: 0 },
	},
	"xiaomi/mimo-v2.6-flash": {
		reasoning: false,
		vision: true,
		efforts: [],
		cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 },
	},
	"xiaomi/mimo-v2.5-pro": {
		reasoning: false,
		vision: false,
		efforts: [],
		cost: { input: 0.435, output: 0.87, cacheRead: 0.0036, cacheWrite: 0 },
	},
	"xiaomi/mimo-v2.5": {
		reasoning: false,
		vision: true,
		efforts: [],
		cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 },
	},
	"nvidia/nemotron-3-ultra-550b-a55b": {
		reasoning: true,
		vision: false,
		efforts: [],
		cost: { input: 0.6, output: 2.4, cacheRead: 0.12, cacheWrite: 0 },
	},
	"claude-fable-5-1": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh", "max"],
		cost: { input: 10, output: 50, cacheRead: 0.25, cacheWrite: 12.5 },
	},
	"claude-fable-5": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh", "max"],
		cost: { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 },
	},
	"claude-opus-5": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh", "max"],
		cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
	},
	"claude-opus-4-8": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh", "max"],
		cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
	},
	"claude-opus-4-7": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh", "max"],
		cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
	},
	"claude-sonnet-5": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh", "max"],
		cost: { input: 2, output: 10, cacheRead: 0.2, cacheWrite: 2.5 },
	},
	"claude-sonnet-4-6": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh", "max"],
		cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
	},
	"claude-haiku-4-5-20251001": {
		reasoning: false,
		vision: true,
		efforts: [],
		cost: { input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 },
	},
	"gpt-6-astra": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh", "max"],
		cost: {
			input: 10,
			output: 50,
			cacheRead: 1,
			cacheWrite: 12.5,
			tiers: [{ inputTokensAbove: 272000, input: 20, output: 75, cacheRead: 2, cacheWrite: 25 }],
		},
	},
	"gpt-5.6-sol": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh", "max"],
		cost: {
			input: 5,
			output: 30,
			cacheRead: 0.5,
			cacheWrite: 6.25,
			tiers: [{ inputTokensAbove: 272000, input: 10, output: 45, cacheRead: 1, cacheWrite: 12.5 }],
		},
	},
	"gpt-5.6-terra": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh", "max"],
		cost: {
			input: 2,
			output: 12,
			cacheRead: 0.2,
			cacheWrite: 2.5,
			tiers: [{ inputTokensAbove: 272000, input: 4, output: 18, cacheRead: 0.4, cacheWrite: 5 }],
		},
	},
	"gpt-5.6-luna": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh", "max"],
		cost: {
			input: 0.2,
			output: 1.2,
			cacheRead: 0.02,
			cacheWrite: 0.25,
			tiers: [
				{ inputTokensAbove: 272000, input: 0.4, output: 1.8, cacheRead: 0.04, cacheWrite: 0.5 },
			],
		},
	},
	"gpt-5.5": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh"],
		cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
	},
	"gpt-5.4": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh"],
		cost: { input: 2.5, output: 15, cacheRead: 0.25, cacheWrite: 0 },
	},
	"gpt-5.4-mini": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high"],
		cost: { input: 0.75, output: 4.5, cacheRead: 0.075, cacheWrite: 0 },
	},
	"gpt-5.3-codex": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh"],
		cost: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 0 },
	},
	"google/gemini-3.8-flash": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high"],
		cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 },
	},
	"google/gemini-3.7-flash": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high"],
		cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0.08334 },
	},
	"google/gemini-3.6-flash": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high"],
		cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 },
	},
	"google/gemini-3.5-flash": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high"],
		cost: { input: 1.5, output: 9, cacheRead: 0.15, cacheWrite: 0 },
	},
	"google/gemini-3.5-flash-lite": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high"],
		cost: { input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: 0 },
	},
	"google/gemini-3.1-flash-lite": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high"],
		cost: { input: 0.25, output: 1.5, cacheRead: 0.03, cacheWrite: 0 },
	},
	"sakana/fugu-ultra": {
		reasoning: true,
		vision: true,
		efforts: ["high", "xhigh"],
		cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
	},
	"meta/muse-spark-1.3": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh", "max"],
		cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 },
	},
	"meta/muse-spark-1.3-contributor": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh"],
		cost: { input: 0.1, output: 0.2, cacheRead: 0.002, cacheWrite: 0 },
	},
	"meta/muse-spark-1.2": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh"],
		cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 },
	},
	"meta/muse-spark-1.2-contributor": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh"],
		cost: { input: 0.1, output: 0.2, cacheRead: 0.002, cacheWrite: 0 },
	},
	"meta/muse-spark-1.1": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh"],
		cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 },
	},
	// 40% off through 2026-09-27; standard rate is 2/6/0.5.
	"xai/grok-4.7": {
		reasoning: true,
		vision: true,
		efforts: [],
		cost: { input: 1.2, output: 3.6, cacheRead: 0.3, cacheWrite: 0 },
	},
	"xai/grok-4.6": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high", "xhigh"],
		cost: {
			input: 2,
			output: 6,
			cacheRead: 0.5,
			cacheWrite: 0,
			tiers: [{ inputTokensAbove: 200000, input: 4, output: 12, cacheRead: 1, cacheWrite: 0 }],
		},
	},
	"xai/grok-4.5": {
		reasoning: true,
		vision: true,
		efforts: ["low", "medium", "high"],
		cost: { input: 2, output: 6, cacheRead: 0.5, cacheWrite: 0 },
	},
	"thinkingmachines/inkling": {
		reasoning: true,
		vision: true,
		efforts: [],
		cost: { input: 1, output: 4.05, cacheRead: 0.17, cacheWrite: 0 },
	},
	"thinkingmachines/inkling-small": {
		reasoning: true,
		vision: true,
		efforts: [],
		cost: { input: 0.5, output: 1.2, cacheRead: 0.1, cacheWrite: 0 },
	},
};